### ISSUE TITLE
Is there a way to use XCEventGenerator in WDA on Xcode11.6

### ISSUE THREAD

**Issue by KevinChan168** [appium/WebDriverAgent#365]
This method in WebDriverAgent/WebDriverAgentLib/Commands/FBElementCommands.m a little bit slow
+ (id<FBResponsePayload>)handleTap:(FBRouteRequest *)request
{
  FBElementCache *elementCache = request.session.elementCache;
  CGPoint tapPoint = CGPointMake((CGFloat)[request.arguments[@"x"] doubleValue], (CGFloat)[request.arguments[@"y"] doubleValue]);
  XCUIElement *element = [elementCache elementForUUID:request.parameters[@"uuid"]];
  if (nil == element) {
    XCUICoordinate *tapCoordinate = [self.class gestureCoordinateWithCoordinate:tapPoint application:request.session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
    [tapCoordinate tap];
  } else {
    NSError *error;
    if (![element fb_tapCoordinate:tapPoint error:&error]) {
      return FBResponseWithStatus([FBCommandStatus invalidElementStateErrorWithMessage:error.description traceback:nil]);
    }
  }
  return FBResponseWithOK();
}

If it is modified to:

+ (id<FBResponsePayload>)handleTap:(FBRouteRequest *)request
{
  //FBElementCache *elementCache = request.session.elementCache;
  CGPoint tapPoint = CGPointMake((CGFloat)[request.arguments[@"x"] doubleValue], (CGFloat)[request.arguments[@"y"] doubleValue]);
  //XCUIElement *element = [elementCache elementForUUID:request.parameters[@"uuid"]];
  //if (nil == element) {
  //  XCUICoordinate *tapCoordinate = [self.class gestureCoordinateWithCoordinate:tapPoint application:request.session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
  //  [tapCoordinate tap];
  //} else {
  //  NSError *error;
  //  if (![element fb_tapCoordinate:tapPoint error:&error]) {
  //    return FBResponseWithStatus([FBCommandStatus invalidElementStateErrorWithMessage:error.description traceback:nil]);
  //  }
  //}
  [[XCEventGenerator sharedGenerator] pressAtPoint:tapPoint forDuration:0 liftAtPoint:tapPoint velocity:1000 orientation:0 name:@"drag" handler:^(XCSynthesizedEventRecord *record,NSError *commandError) {}];
  return FBResponseWithOK();
}

The click action would be much more faster, however this code only working on version below Xcode 10.1 since XCEventGenerator has been removed since Xcode10.2

In version higher than 10.1 would get following error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCEventGenerator", referenced from:
      objc-class-ref in FBCustomCommands.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The workaround mention in this works for tap, but caused crash on test startup
https://github.com/facebook/idb/issues/553
I wonder whether there is a way to make it working in latest in Xcode 11.6

**Comment by harrain** [comment]
copy XCTest.framework of Xcode10.1 into Xcode11.6

**Comment by KazuCocoa** [comment]
Yeah, probably copy may help.
But as this repository, we won't copy removed code as a workaround

**Comment by KazuCocoa** [comment]
Close this with adding a label
