### ISSUE TITLE
🐞 bug: WDA build fails on iOS 26.2 with Xcode 26.2 – Identifier '_XCTSetApplicationStateTimeout' is reserved

### ISSUE THREAD

**Issue by SIF-Nachiket** [appium/WebDriverAgent#1088]
Bug Description: 
WebDriverAgent fails to build on iOS 26.2 devices due to a compilation error related to XCTest private APIs.
 
iOS 26.0.1 and iOS 26.1 work correctly with the same Appium setup.
Initially, Xcode 16.2 was used where iOS 26.0.1 and 26.1 worked, but iOS 26.2 did not.
To rule out Xcode/macOS compatibility, we upgraded both macOS and Xcode to 26.2, but the issue still persists.
 
This confirms the issue is specific to iOS 26.2 and WebDriverAgent compatibility.

Environment :
macOS: 26.2
Xcode: 26.2
iOS Devices:
iOS 26.0.1 → working on xcode16.2
iOS 26.1 → working on xcode16.2
iOS 26.2 → failing on xcode16.2
Appium: 2.17.1
appium-xcuitest-driver: 9.1.0
WebDriverAgent: bundled with Appium
Node.js: 23.x

Error Observed :
During WebDriverAgent build on iOS 26.2, the following error occurs:
**Identifier '_XCTSetApplicationStateTimeout' is reserved because it starts with '_' followed by a capital letter**
Due to this error, WDA fails to build and Appium automation execution cannot proceed on iOS 26.2 devices.

WebDriverAgent should successfully build and run on iOS 26.2 devices, similar to iOS 26.0.1 and iOS 26.1.

Additional Notes : 
WebDriverAgent launches successfully when run manually via Xcode.
Automation fails only during Appium execution on iOS 26.2.
Issue persists even after upgrading macOS and Xcode to 26.2.
This appears to be a breaking XCTest change introduced in iOS 26.2.

**Comment by SIF-Nachiket** [comment]
Hi team,
 
This issue seems to be related to WebDriverAgent compatibility with iOS 26.2.
Could you please add appropriate labels such as 'bug', 'WebDriverAgent', and 'iOS'?
 
Thanks!

**Comment by KazuCocoa** [comment]
Is it the same as https://github.com/appium/WebDriverAgent/issues/839?
What I observed in the past was fixed with https://github.com/appium/WebDriverAgent/pull/1032 . It might be environment-dependent, like building a cache as well.


> appium-xcuitest-driver: 9.1.0

The version you addressed has `appium-webdriveragent` 9.3.3, so it doesn't have the fix PR.
https://www.npmjs.com/package/appium-xcuitest-driver/v/9.1.0?activeTab=code
Please try out with newer versions

**Comment by SIF-Nachiket** [comment]
Thank you for your feedback.

Update:
 
WebDriverAgent builds successfully after upgrading appium-xcuitest-driver to 9.10.x.
 
Automation works correctly on iOS 26.0.1 and iOS 26.1 using the same setup.
 
The issue persists only on iOS 26.2 during runtime (session/app launch). 

This suggests a behavioral change in XCTest introduced in iOS 26.2 rather than a build or configuration issue.

I have attached the relevant Appium logs below from the iOS 26.2 failure for reference.
 
Please let us know if there is any recommended workaround or if additional information is required.

[iOS26_2 device issue.txt](https://github.com/user-attachments/files/24237061/iOS26_2.device.issue.txt)

**Comment by mykola-mokhnach** [comment]
I've just updated Xcode to 26.2 and observe no build issues. Also, I don't see any build issues in the log attached above. Please provide the correct log containing the described error traceback

**Comment by KazuCocoa** [comment]
If you mentioned like
> [8ec7f3f8][RemoteDebugger] Received data response from send (id: 54): '{"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":54}'
[8ec7f3f8][RemoteDebugger] Sending to Web Inspector took 5ms

lines, it is duplicate of https://github.com/appium/appium/issues/21705 - please use XCUITest driver 10.5.0+.
As https://github.com/appium/appium-xcuitest-driver/blob/master/CHANGELOG.md#1050-2025-11-11, it has a fix for iOS 26.2.

Closing as currently addressed ones are already in our fixes.

**Comment by SIF-Nachiket** [comment]
Thank you for the clarification and quick response.
 
upgrading to appium-xcuitest-driver 10.5.0+ resolves the iOS 26.2 runtime issue.
After upgrading, automation is working as expected on iOS 26.2.
 
Thanks for pointing to the related issue and changelog.
Closing this from our side as resolved.
